MYCONF+=(
 #--target=${CHOST}
 #--disable-multilib
 --enable-static
 --disable-shared
 --enable-languages=c,c++
 --disable-libssp
 --disable-libquadmath
 #--disable-libstdcxx-pch
 --disable-libstdcxx
 --disable-libatomic
 --enable-bootstrap
 --disable-libgomp
)