#!/bin/sh
# Support [experimental]: newbin from ebuild (minimal)
# Usage: newbin <old file> <new filename>
# Variables: ED DESTTREE
# default path is ${ED}${DESTTREE}/bin/
# https://devmanual.gentoo.org/eclass-reference/ebuild/
# Date: 2026-02-09 21:00 UTC - last change

IFS="$(printf '\n\t') "
SC=${0##*/}
ED=${ED:-$INSTALL_DIR}

: ${ED:?required install dir variables} ${DESTTREE:-}
: ${1:?Usage: $SC <old file> <new filename>... Error}
: ${2:?Usage: $SC <old file> <new filename>... Error}

if [ ${#} -ne '2' ];then
  printf '%s\n' "Usage: $SC  <old file> <new filename>... Error" >&2
  exit 1
fi

mkdir -pm 0755 -- "${ED}${DESTTREE}/bin/"

mv -n "${1}" "${ED}${DESTTREE}/bin/${2}" &&

printf %s\\n "${SC}: mv -n ${1} ${ED}${DESTTREE}/bin/${2}" ||
{ printf %s\\n "${SC}: mv -n ${1} ${ED}${DESTTREE}/bin/${2}... Error" >&2; exit 1;}
