#!/bin/sh
# Support [experimental]: newexe from ebuild (minimal)
# Usage: newexe <old file> <new filename>
# Variables: ED _E_EXEDESTTREE_
# default path is ${ED}${_E_EXEDESTTREE_}/
# https://devmanual.gentoo.org/eclass-reference/ebuild/
# Date: 2024-06-01 16:00 UTC - last change

IFS="$(printf '\n\t') "
SC=${0##*/}
ED=${ED:-$INSTALL_DIR}

: ${ED:?required install dir variables} ${_E_EXEDESTTREE_:-}
: ${1:?Usage: $SC <old file> <new filename>... Error}
: ${2:?Usage: $SC <old file> <new filename>... Error}

if test "${#}" -ne '2';then
  printf '%s\n' "Usage: $SC  <old file> <new filename>... Error" >&2
  exit 1
fi

mkdir -pm 0755 -- "${ED}${_E_EXEDESTTREE_}/"

mv -n "${1}" "${ED}${_E_EXEDESTTREE_}${2}" &&

printf %s\\n "${SC}: mv -n ${1} ${ED}${_E_EXEDESTTREE_}${2}" ||
{ printf %s\\n "${SC}: mv -n ${1} ${ED}${_E_EXEDESTTREE_}${2}... Error" >&2; exit 1;}
