#!/bin/sh
# Copyright (C) 2021-2025 Artjom Slepnjov, Shellgen
# License GPLv3: GNU GPL version 3 only
# http://www.gnu.org/licenses/gpl-3.0.html
# Date: 2023-12-08 20:00 UTC - last change

NL="$(printf '\n\t')"; NL=${NL%?}; IFS=${NL}
XABI=${ABI} DBFILE="/var/db/pkgs.db"
BUILD_CHROOT=${BUILD_CHROOT:-0} BUILDLIST=${BUILDLIST}
DIRS= PKGS= MOUNTLIST= DIR= PKG= XLIBABI=

{ test "X${USER}" != 'Xroot' || test "${BUILD_CHROOT:=0}" -ne '0' ;} && { USE_BUILD_ROOT='0'; exit;}

EXITCODE="1"
BUILD_CHROOT="0"
DIRS="dev${NL}dev/shm${NL}pkg${NL}proc${NL}sys${NL}usr/distfiles"
PKGS="sys-apps/busybox"

MOUNTLIST=
while IFS= read -r STRING; do
  MOUNTLIST="${MOUNTLIST:+${MOUNTLIST}${NL}}${STRING}"
done < '/proc/mounts'
MOUNTLIST="${MOUNTLIST:+${NL}${MOUNTLIST}${NL}}"

for DIR in $(findmountdir "${PDIR}"); do
  'runverb' umount "${DIR}"
done

cpuonline '1'

printf %s\\n "ABI_BUILD='${ABI_BUILD}'" "ABI='${ABI}'" "XABI='${XABI}'"
printf %s\\n "LIB_DIR='${LIB_DIR}'" "LIBDIR='${LIBDIR}'"

XLIBABI='lib'
case ${ABI_BUILD} in
  'x32')
    XLIBABI='libx32'
  ;;
  'x86')
    XLIBABI='lib32'
    test -e "${PDIR}/${XLIBABI}" || ln -sf lib ${PDIR}/${XLIBABI}
  ;;
  'amd64')
    XLIBABI='lib64'
  ;;
esac

for DIR in usr ${DIRS} bin etc lib ${XLIBABI} opt sbin var tmp var/log; do
  test -n "${DIR}" || continue
  test -d "${PDIR}/${DIR}" && continue
  test -L "${PDIR}/${DIR}" && continue
  mkdir -m '0755' ${PDIR}/${DIR}/
done
chmod 1777 ${PDIR}/tmp/
test -e "${PDIR}/usr/bin"        || ln -sf ../bin        ${PDIR}/usr/bin
test -e "${PDIR}/usr/lib"        || ln -sf ../lib        ${PDIR}/usr/lib
test -e "${PDIR}/usr/${XLIBABI}" || ln -sf ../${XLIBABI} ${PDIR}/usr/${XLIBABI}
test -e "${PDIR}/usr/sbin"       || ln -sf ../sbin       ${PDIR}/usr/sbin

cp -urp /mnt/root/bin/ /mnt/root/etc/ /mnt/root/lib/ /mnt/root/opt/ /mnt/root/sbin/ /mnt/root/var/ ${PDIR}/ &&
printf %s "cp -urp /mnt/root/bin/ /mnt/root/etc/ /mnt/root/lib/ " &&
printf %s\\n "/mnt/root/opt/ /mnt/root/sbin/ /mnt/root/var/ ${PDIR}/"

for DIR in ${DIRS}; do
  test -n "${DIR}" || continue
  findblkdev "${PDIR}/${DIR}" && continue
  case ${PDIR}/${DIR} in
    "${PDIR}/dev"|"${PDIR}/sys"|"${PDIR}/proc")
      mount -nio 'bind,ro' /${DIR}/ "${PDIR}/${DIR}/"
      mount -nio 'remount,ro' "${PDIR}/${DIR}/"
    ;;
    *)
      mount -nio 'bind' /${DIR}/ "${PDIR}/${DIR}/"
    ;;
  esac &&
  printf %s\\n "mount -nio bind /${DIR}/ ${PDIR}/${DIR}/"
done
test -x "${PDIR}/lib/ld-musl-x32.so.1" || >"${PDIR}/${DBFILE:?}"  # pkg db file init for bootstrap

for PKG in ${PKGS}; do
  PKG=${PKG%%#*}
  PKG="${PKG#${PKG%%[![:space:]]*}}"
  test -n "${PKG}" || continue
  XABI=${ABI_BUILD}
  if ABI=${XABI} pkg-is ${PKG} >/dev/null; then
    :
  else
    XABI="x32"
  fi
  ABI=${XABI} ROOT_DIR=${PDIR} spkg ${PKG}
done
XABI=${ABI}
test -n "${BUILDLIST}" && BUILDLIST='1'

printf %s "ABI=${ABI_BUILD} LIBDIR=/${XLIBABI} LIB_DIR=${XLIBABI} USE_BUILD_ROOT=${USE_BUILD_ROOT}"
printf %s\\n " BUILD_CHROOT=1 XPWD=${PDIR} BUILDLIST=${BUILDLIST} chroot ${PDIR}/ /build-script.sh"

#export USER XPN PF PV WORKDIR PKGNAME DPREFIX BUILD_CHROOT LC_ALL BUILD_USER SRC_DIR IUSE SRC_URI PATH
#export XABI SPREFIX EPREFIX DPREFIX PDIR P SN PN PORTS_DIR DISTDIR DISTSOURCE FILESDIR INSTALL_DIR S SDIR

XPWD=${PDIR} \
PDIR='/' \
PATH='/sbin:/bin:/opt/sbin:/opt/bin:/misc.d:/etools.d' \
ABI=${ABI_BUILD} \
LIBDIR="/${XLIBABI}" \
LIB_DIR=${XLIBABI} \
USE_BUILD_ROOT=${USE_BUILD_ROOT} \
BUILD_CHROOT='1' \
BUILDLIST=${BUILDLIST} \
chroot ${PDIR}/ '/build-script.sh' && EXITCODE="0"

MOUNTLIST=
while IFS= read -r STRING; do
  MOUNTLIST="${MOUNTLIST:+${MOUNTLIST}${NL}}${STRING}"
done < '/proc/mounts'
MOUNTLIST="${MOUNTLIST:+${NL}${MOUNTLIST}${NL}}"

for DIR in '' ${DIRS}; do
  test -n "${DIR}" || { DIRS=; continue;}
  DIRS="${DIR}${DIRS:+${NL}${DIRS}}"
done

for DIR in $(findmountdir "${PDIR}"); do
  usleep 100000
  'runverb' umount "${DIR}"
  DIR="${DIR#${PDIR}/}"
  #test -n "${DIR}" &&
  #case ${MOUNTLIST} in
  #  *" ${PDIR}/${DIR} "*) 'runverb' umount ${PDIR}/${DIR}/;;
  #esac
  case ${PDIR}/${DIR} in
    "${PDIR}/dev"|"${PDIR}/sys"|"${PDIR}/proc")
      mount -nio 'remount,rw' "/${DIR}/"
    ;;
  esac
done

USE_BUILD_ROOT='0'

test "0${EXITCODE}" -eq '0'
