#!/bin/sh
# Copyright (C) 2021-2023 Artjom Slepnjov, Shellgen
# License GPLv3: GNU GPL version 3 only
# http://www.gnu.org/licenses/gpl-3.0.html
# Date: 2023-10-07 18:00 UTC - fix: near to compat-posix, no-posix: header file <<!/bin/bash>>, getent

NL="$(printf '\n\t')"; NL=${NL%?}

MKSRCDIR='mksrc.d' SKIPLIST= CDPHASEUSER= P=

: ${USER:=root} ${USE_BUILD_ROOT:=1} ${BUILD_CHROOT:=0}

export USER BUILDLIST XPN

if test "x${USER}" != 'xroot'; then
  #test "${BUILD_CHROOT:=0}" -ne '0' || cd ${XPWD%/}/
  nslookup 'play.google.com' 1.1.1.1 &&
  { printf %s\\n "network: work... error"; exit 1;}
  #. ${ENV:?}
elif test ! -x 'mksrc.sh'; then
  printf '\n\n\n\n######################################\n' >> /var/log/mksrc.log
  # early exist is: SKIPLIST
  printf %s\\n "cp -ur ../../'mksrc.sh' ../../profiles/* ."
  cp -ur ../../'mksrc.sh' ../../profiles/* .
  # test: replace from in old [pre <cp> copy] --> is
  test -s 'removelist.lst' &&
  {
    while IFS= read -r X; do
      SKIPLIST="${SKIPLIST:+${SKIPLIST}${NL}}${X%%#*}"
    done < 'removelist.lst'
    # may be bug to such as: clean located is file: `&>>` =- `>`
    for P in ${SKIPLIST}; do >"${P:=.skip}"; done
  }
fi

printf %s\\n "PWD='${PWD}'" "USER='${USER}'" "MKSRCDIR='${MKSRCDIR}'"
