#!/bin/sh
# Copyright (C) 2023-2025 Artjom Slepnjov, Shellgen
# License GPLv3: GNU GPL version 3 only
# http://www.gnu.org/licenses/gpl-3.0.html
# Date: 2023-10-04 18:00 UTC, 2025-12-09 18:00 UTC - fix: near to compat-posix, no-posix: local VAR

NET_USER="clearnet"
RUN="pkg_fetch"

test "0${BUILD_CHROOT}" -ne '0' || exit 0
test "X${USER}" != 'Xroot' && exit

>>"checksums".lst

mkdir -pm '0755' -- "${DISTSOURCE:?}/"
# Swith User Network - nopriv
test -d "${DISTSOURCE}" && chown ${NET_USER}:${NET_USER} "${DISTSOURCE}/"
test -d "${DISTDIR}"    && chown ${NET_USER}:${NET_USER} "${DISTDIR}/"
chown ${NET_USER}:${NET_USER} checksums.lst

RUN=$(type ${RUN})
RUN=${RUN##* }
USE_BUILD_ROOT="0"

test "x${RUN}" = 'xbuiltin' && exit

# 1=XPWD 2=BUILD_CHROOT 3=USE_BUILD_ROOT 4=PDIR 5=DISTSOURCE 6=DISTDIR 7=HOME 8=USER 9=LOGNAME 10=PWD
# 11=PV 12=PN 13=XPN 14=XPV 15=CATEGORY 16=GITCOMMIT 17=COMMIT
HOME=${PWD} \
SRC_URI="${1-}" \
su "${NET_USER:?}" -s "${RUN}" \
 "${XPWD:?}" \
 "${BUILD_CHROOT:?}" \
 "${USE_BUILD_ROOT:?}" \
 "${PDIR:?}" \
 "${DISTSOURCE}" \
 "${DISTDIR:?}" \
 "${PWD}" \
 "${NET_USER}" \
 "${NET_USER}" \
 "${PWD}" \
 "${PV}" \
 "${PN}" \
 "${XPN}" \
 "${XPV}" \
 "${CATEGORY}" \
 "${GITHASH}" \
 "${HASH}" || { printf '%s\n' "HOME=${PWD} su ${NET_USER} -s ${RUN}: failed... error"; exit 1;}

test -d "${DISTSOURCE}"  && chown -hR root:root "${DISTSOURCE}/"
test -d "${DISTDIR}"     && chown root:root "${DISTDIR}/"
test -e "checksums.lst"  && chown root:root "checksums.lst"
test -e "src_uri.lst"    && chown root:root "src_uri.lst"
