#!/bin/sh
# 2023-2026
# Date: 2026-02-09 21:00 UTC - last change

SRCLIST=${1:-$SRCLIST}; SRCLIST=${SRCLIST:-src_uri.lst}
PATCH_URI=${PATCH_URI:-$PATCHES_URI}  # it if wrong
PATCH_URI="${PATCH_URI:-http://data.gpo.zugaina.org/gentoo/${CATEGORY}/${PN}/files}"

use 'bundled' && set -- "src_uri_bundled.lst"

if test "X${USER}" = 'Xroot' && test -n "${SRC_URI}"; then
  # Remove only spaces from the beginning of the string.
  printf %s\\n "${SRC_URI#${SRC_URI%%[![:space:]]*}}" > "${SRCLIST}"

  for i in ${PATCHES}; do
    i="${PATCH_URI}/${i##*/}"
    printf %s\\n "${i}" >> "${SRCLIST}"
  done
fi
[ -e "${SRCLIST}" ] || exit 0  # FIX: src_uri.lst: not found

read -r PF < "${SRCLIST}"

# FIX: remove comment in filename
PF="${PF%% #*}"
PF="${PF%${PF##*[![:space:]]}}"

PF=${PF##*[/ ]}  # it must be only the filename

printf %s\\n "${PF:?required filename for: <PF>}"
