#!/bin/sh

export LC_ALL='C'
export MAKEFLAGS='--jobs=4 --load-average=4 -s V=0'
export BUILD_USER='tools'
export SRC_DIR='build'

export CFLAGS='-O2 -msse2 -fno-stack-protector -g0'
export CPPFLAGS='-O2 -msse2 -fno-stack-protector -g0'
export CXXFLAGS='-O2 -msse2 -fno-stack-protector -g0'
export FCFLAGS='-O2 -msse2 -fno-stack-protector -g0'
export FFLAGS='-O2 -msse2 -fno-stack-protector -g0'

export IONICE_COMM='nice -n 19'
