#!/bin/sh
# Copyright (C) 2021-2026 Artjom Slepnjov, Shellgen
# License GPLv3: GNU GPL version 3 only
# http://www.gnu.org/licenses/gpl-3.0.html
# Date: 2024-07-07 19:00 UTC, 2025-12-09 18:00 UTC - last change

SCBUILD=${SCBUILD:-build-script.sh} LOGFILE=${LOGFILE-} BUILDLIST=${BUILDLIST-} F=

[ "0${BUILD_CHROOT}" -ne '0' ] || exit 0
[ "X${USER}" != 'Xroot' ] && { USE_BUILD_ROOT='0'; exit;}

[ -d "${PDIR:?}" ] || { printf '%s\n' "${PDIR-}: dir not found... error" >&2; exit 1;}
cd "${PDIR%/}/"

LOGFILE='/var/log/mkconfig.log'

: ${SRC_DIR:?} ${INSTALL_DIR:?}

[ -n "${BUILD_USER-}" ] || { printf '%s\n' "user: '${BUILD_USER-}': not found... error" >&2; exit 1;}
[ -f "${LOGFILE:?}" ] || > ${LOGFILE:?}
chown ${BUILD_USER}:${BUILD_USER} "${LOGFILE}"

>>'checksums'.lst
>>'src_uri'.lst

mkdir -pm '0755' -- "${SRC_DIR}/" "${INSTALL_DIR}/" "${DISTSOURCE:?}/"
# Swith User - nopriv
[ -d "${SRC_DIR}" ]     && chown -R ${BUILD_USER}:${BUILD_USER} "${SRC_DIR}/"
[ -d "${INSTALL_DIR}" ] && chown -hR ${BUILD_USER}:${BUILD_USER} "${INSTALL_DIR}/"
[ -d "${DISTSOURCE}" ]  && chown ${BUILD_USER}:${BUILD_USER} "${DISTSOURCE}/"  # future - remove
[ -s "checksums.lst" ] ||
{
  chown ${BUILD_USER}:${BUILD_USER} checksums.lst
}

USE_BUILD_ROOT='0'

[ -n "${BUILDLIST}" ] && BUILDLIST='1'
[ -e '/etc/profile' ] && rm -- '/etc/profile'
sed -e "/^${BUILD_USER}:/ s|::/:/bin/sh$|::${PDIR%/}/${SRC_DIR}:/bin/sh|" -i /etc/passwd
printf %s\\n "PWD='${PWD}'"

# 1=ABI_BUILD 2=LIBDIR 3=LIB_DIR 4=PDIR 5=XPWD 6=XPN 7=BUILD_CHROOT
#  8=_ENV 9=USE_BUILD_ROOT 10=BUILDLIST 11=CATEGORY 12=PN
# is required fix when be change <workdir>: HOME=${PDIR%/}/${SRC_DIR} -> HOME=${WORKDIR}
USER=${BUILD_USER} \
HOME="${PDIR%/}/${SRC_DIR}" \
UID="$(finduserid ${BUILD_USER})" \
su ${BUILD_USER} -s "${PWD%/}/${SCBUILD}" \
  "${ABI_BUILD:?}" \
  "${LIBDIR:?}" \
  "${LIB_DIR:?}" \
  "${PDIR:?}" \
  "${XPWD:?}" \
  "${XPN:?}" \
  "${BUILD_CHROOT:?}" \
  "${_ENV-}" \
  "${USE_BUILD_ROOT:?}" \
  "${BUILDLIST-}" \
  "${CATEGORY:?}" \
  "${PN:?}" || { printf '%s\n' "su ${BUILD_USER} -s ${PWD%/}/${SCBUILD}: failed... error" >&2; exit 1;}
