#!/bin/sh
# 2023-2024
# Usage: INST_ABI=$(test-native-abi) pkg-create-cgz
# Date: 2023-12-07 19:00 UTC - last change

LIB_DIR=$(get_libdir) XABI='all' ABI=$(tc-abi) ABI_BUILD=$(tc-abi-build) ED=${INSTALL_DIR}

: ${LIB_DIR:?} ${ABI_BUILD:?} ${ABI:?}
: ${BUILD_CHROOT:=0}  # compat for old build-script

{ test "X${USER}" != 'Xroot' || test "0${BUILD_CHROOT:?}" -ne '0' ;} && exit

test -d "${ED:?}" || exit
cd "${ED}/"

export INST_ABI=${ABI}

ABI=${ABI_BUILD}; INST_ABI=${ABI}

PLIST=
for P in "bin/" "${LIB_DIR}/" "libx32/" "lib32/" "lib64/" "lib/" "sbin/" "opt/" "usr/libexec/"; do
  test -d "${P}" && PLIST="${PLIST:+${PLIST}${IFS}}$(globstar ${P})"
done

# skip it: [elf32-i386] for the <grub2> through the <bios-legacy>
# native may be: elf32_x86_64 [elf32-x86-64], elf64_x86_64 [elf64-x86-64], elf_i386 [elf32-i386]
for P in ${PLIST}; do
  case /${P} in
    *"/pkgconfig/"*".pc") XABI='all'; continue
    ;;
    *"/i386-pc/"*) XABI='all'; continue
      # skip: lib*/grub/i386-pc/*.mod [elf32-i386]
    ;;
    "/lib/"?*)
      XABI='all'
      # error: <LIB_DIR> != lib - correct of fix --> lib32
      test "X${ABI}" = 'Xx86' || continue
      XABI=${ABI}
    ;;
    "/${LIB_DIR}/"?* | "/libx32/"?* | "/lib32/"?* | "/lib64/"?* ) XABI=${ABI}
    ;;
  esac
  if testelf ${P}; then
    XABI=${ABI}; break
  fi
done

test "X${XABI}" = 'Xall' && INST_ABI=${XABI}

printf %s\\n "${INST_ABI:?}"
