#!/bin/sh
# Copyright (C) 2021-2024 Artjom Slepnjov, Shellgen
# License GPLv3: GNU GPL version 3 only
# http://www.gnu.org/licenses/gpl-3.0.html
# Usage: ABI=${ABI} ROOT_DIR=${ROOT_DIR} PKG_DIR=${PKG_DIR} pkginst ${CATEGORY}/${PN} ${CATEGORY}/${PN}
# Date: 2024-04-11 14:00 UTC - last change
# Date: 2024-11-11 21:00 UTC - last change

IFS="$(printf '\n\t')"; IFS=${IFS%?} RUN='spkg'
EXIT='exit' RUN=${RUN##*/} OLDPWD=${OLDPWD} EXITCODE='0' ERRO=
ABI=${ABI:=x32} ROOT_DIR=${ROOT_DIR:=/} PKG_DIR=${PKG_DIR} X= PKGS= PKG= XROOT_DIR= BINDIR=
ZCOMP='lzop' DBFILE="${ROOT_DIR%/}/var/db/pkgs.db" NL= FN= CPN= PABI=
ERRO="\e[0;31m +\e[0;36m ${RUN}\e[m... \e[0;31merror\e[m\n"

test "X${USER}" != 'Xroot' && exit
test "${BUILD_CHROOT:=0}" -eq '0' && exit

_XERROR(){ printf "${RUN} \e[0;33m--install\e[0;36m ${FN}\e[m... \e[0;31merror\e[m\n";}

X='u' # update pkg default
test "${RUN#${RUN%-force}}" = '-force' && X='u'

for PKG_DIR in ${PKG_DIR:=/pkg} '/pkg' '/pkg'* '/mnt/root/pkg' '/mnt/'*'/pkg'; do
  test -d "${PKG_DIR%/}" && break
done

for PKG in ${@}; do
  PKG=${PKG%%[ \#]*}  # testing
  P=
  test -d "/bundled" && P="$(printf /bundled/${PKG}_*[0-9]*_${ABI}.c[glx]z)"
  test -f "${P}" || P="$(printf ${PKG_DIR}/${PKG}_*[0-9]*_${ABI}.c[glx]z)"
  test -f "${P}" || P="$(printf ${PKG_DIR}/${PKG}_*[0-9]*_x32.c[glx]z)"
  test -f "${P}" || P="$(printf ${PKG_DIR}/${PKG}_*[0-9]*_amd64.c[glx]z)"
  test -f "${P}" || P="$(printf ${PKG_DIR}/${PKG}_*[0-9]*_x86.c[glx]z)"
  test -f "${P}" && PKGS="${PKGS:+${PKGS}${IFS}}${P}"

  P="$(printf ${PKG_DIR}/${PKG}_*[0-9]*_all.c[glx]z)"
  test -f "${P}" && PKGS="${PKGS:+${PKGS}${IFS}}${P}"
done

cd ${ROOT_DIR} || exit

for PKG in ${PKGS}; do
  test -e "${PKG}" || continue
  FN="${PKG#${PKG%/*/*}/}"; CPN=${FN%%_*}; PABI="${PKG#${PKG%_*}_}"; PABI=${PABI%.*}
  P="${ROOT_DIR%/}/etc/postinst.d/${CPN}.env"
  check-pkg "${CPN} ${PABI}" >/dev/null && continue
  case ${PKG} in
    *'.cxz')
      ZCOMP='unxz'
    ;;
    *'.clz')
      ZCOMP='lzop'
    ;;
    *'.cgz'|*'.cpio.gz')
      ZCOMP='gunzip'
    ;;
  esac
  ${ZCOMP} -dc ${PKG} | cpio -${X}im 2> /dev/null || { EXITCODE='1'; _XERROR; continue;}
  test -s "${P}" && . ${P} && printf '%s\n' "${P}... ok"
  NL=${IFS}
  printf "${CPN} ${PABI}${NL}" >> ${DBFILE}
  printf "${RUN} \e[0;33m--install\e[0;31m ${FN}\e[m... \e[0;33mok\e[m\n"
done
test "${EXITCODE}" -eq '0'
