#!/bin/sh
# Usage: ARCH=$(tc-arch)
# Return: printf ARCH |  Exitcode: [true]/[false]
# Date: 2023-12-07 08:00 UTC - last change

test -z "${ARCH}" &&

case $(tc-getCC 2>/dev/null) in
  'gcc')
    CC_ARCH=$(gcc -dumpmachine)
  ;;
  'tcc')
    CC_ARCH=$(tcc --version)
    CC_ARCH=${CC_ARCH#*[(]}
    CC_ARCH=${CC_ARCH%[)]*}
  ;;
  *)
    CC_ARCH='i686'
  ;;
esac &&

case ${CC_ARCH} in
  i?86*)
    ARCH='i686'
  ;;
  'x86_64'*|'x86-64'*)
    ARCH='x86_64'
  ;;
  *)
    ARCH=$(uname -m)
  ;;
esac &&

printf %s\\n "${ARCH:?}"
