#!/bin/sh
# Date: 2023-12-03 19:00 UTC - last change
# Support [experimental]: EAPI-4 (minimal)
# Usage: use_with !{useflag-global} {useflag-local:optional} [configure+opt]
# Return: --with-${useflag} / --without-${useflag}  |  Exitcode: [true]/[false]
# https://devmanual.gentoo.org/eclass-reference/ebuild/index.html

: ${PDIR:?} ${CATEGORY:?} ${PN:?} ${1:?required global useflag}

IFS="$(printf '\n\t')"; IFS=${IFS%?}
LOFLAG="${2-${1}}"
OPT="${3}"

test -d "${PDIR%/}/package.use" || PDIR='/'  # may the no need?

FLAGS=
for S in "${PDIR%/}/package.use/"*; do
  test -f "${S}" &&
  while IFS= read -r S; do
    S=${S%%#*}
    S="${S%${S##*[![:space:]]}}"
    X=${S%%: *}
    test -n "${S}" &&
    case ":${CATEGORY}/${PN}:" in
      :${S%%: *}:|:${S%/\**}/*|${S%\*/\**}:*/*|*/${X#*\*/}:)
        S="${S#${S%%: *}: }"
        FLAGS="${FLAGS:+${FLAGS} }${S#${S%%[![:space:]]*}}"
      ;;
    esac
  done < ${S}
done

IFS=" ${IFS%?}"

for S in ${IUSE} ${FLAGS} ${USE}; do
  case ${S} in
    "+${1}") BUILDFLAG="--with-${LOFLAG}${OPT:+=${OPT}}"
    ;;
    "-${1}") BUILDFLAG="--without-${LOFLAG}"
    ;;
    "+${1#!}") BUILDFLAG="--without-${LOFLAG}"
    ;;
    "-${1#!}") BUILDFLAG="--with-${LOFLAG}${OPT:+=${OPT}}"
    ;;
  esac
done

printf %s\\n "${BUILDFLAG:=--without-${LOFLAG}}"; test "x${BUILDFLAG-}" = "x--with-${LOFLAG}"
