#!/bin/sh
# Support [experimental]: EAPI-8 (minimal)
# Usage: dosym [-r] <filename> <linkname>
# https://devmanual.gentoo.org/eclass-reference/ebuild/
# Date: 2024-05-23 19:00 UTC - last change

# options: -r creates a relative symlink.

IFS="$(printf '\n\t') "
SC=${0##*/}
ED=${ED:-$INSTALL_DIR}
OPT=

: ${ED:?required install dir variables} ${1:?Usage: $SC  [-r] <filename> <linkname>... Error}

test "X${1}" = 'X-r' && { OPT=${1}; shift;}

if test "${#}" -ne '2';then
  printf '%s\n' "Usage: $SC  [-r] <filename> <linkname>... Error" >&2
  printf '%s\n' "\$3? ambiguous [$SC \$1 \$2]... Error" >&2
  exit 1
fi

printf %s "${SC}: ln -s ${OPT} ${1} ${ED}${2}"
ln -s ${OPT} ${1} "${ED}"${2} ||

{ printf %s\\n "... Error" >&2; exit 1;}

printf '\n'
