MYCONF="${MYCONF}
 --enable-removal-policies=lru,heap
 --enable-storeio=ufs
 --enable-disk-io
 --disable-auth
 --disable-auth-basic
 --disable-auth-digest
 --disable-auth-ntlm
 --disable-auth-negotiate
 #--disable-external-acl-helpers
 #--disable-log-daemon-helpers
 #--disable-url-rewrite-helpers
 --disable-cache-digests
 --disable-delay-pools
 --disable-eui
 --disable-icmp
 --disable-follow-x-forwarded-for
 #--without-large-files
 --with-build-environment=default
 #--disable-large-cache-files
 --disable-strict-error-checking
 --disable-arch-native
 --disable-unlinkd
 --disable-internal-dns
 --disable-epoll
 --disable-select
 --enable-poll
 --disable-loadable-modules
 --disable-translation
 #--disable-auto-locale
 --disable-forw-via-db
 #--disable-useragent-log
 #--disable-referer-log
 #--disable-forward-log
 --disable-arp-acl
 --disable-cachemgr
 --disable-ident-lookups
 --disable-regex
 --enable-gnuregex
 --without-nettle
 --with-openssl
 #--with-gnutls
 --disable-stacktraces
 --without-libcap
 --disable-snmp
 --disable-ssl-crtd
 --disable-ecap
 --disable-esi
 --disable-htcp
 --disable-wccp
 --disable-wccpv2
 #--without-dl
"
