CPPFLAGS="${CPPFLAGS:+${CPPFLAGS} }-DSQLITE_ENABLE_FTS3_TOKENIZER=1"
CPPFLAGS="${CPPFLAGS:+${CPPFLAGS} }-DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_SECURE_DELETE"
CPPFLAGS="${CPPFLAGS:+${CPPFLAGS} }-DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1"

{ test "x${USER}" != 'xroot' || test "${USE_BUILD_ROOT:=0}" -ne '0' ;} || return 0
# ok - color: green
printf " \e[1;32m+\e[m ${SCNAME##*/}... ok\n"
