#!/bin/sh
# 2019-2026
# File: /sbin/build
# compatible with Linux kernel (Linuxism)
# Usage: USE=+bootstrap EABI=x86  emerge -b -- ${CATEGORY}/${PN} ${CATEGORY}/${PN} @system @world @libs
# Usage: USE=+x32 EABI=x32  emerge -b -- ${CATEGORY}/${PN} ${CATEGORY}/${PN} @system @world @libs
# Usage: USE='-static -static-libs +shared -lfs +patch -doc -diet +musl +strip +x32' build -b -- dev-libs/libzip
# Date: 2023-12-09 11:00 UTC, 2026-02-04 10:00 UTC - last change

export BUILD_USER PORTS_DIR PORTS_TMPDIR CATEGORY PN HOSTNAME

EXIT='exit'
X=${*}
IFS="$(printf '\n\t')"; IFS="${IFS%?} "
HOSTNAME="localhost"
BUILD_USER=${BUILD_USER:-tools}
PORTS_DIR="/usr/ports"
TMPDIR="/var/tmp"
PORTS_TMPDIR="/var/tmp/ports"
LOGFILE="/var/log/mksrc.log"

test -n "${FUNCNAME-}" && EXIT='return'

check_arch(){
  local ARCH

  for EABI in x32 x86 amd64 ''; do
    case " ${USE} " in *" +${EABI} "*) break;; esac
  done
  export ABI=${EABI} EABI

  case ${EABI} in
    'x86'|'32')
      ARCH='i686'
    ;;
    'x32'|'amd64'|'x86_64'|'x86-64')
      ARCH='x86_64'
    ;;
    *)
      ARCH=$(uname -m)
    ;;
  esac
  printf %s\\n "${ARCH:?}"
}

[ -n "${TMPDIR:?required <TMPDIR>}" ] || ${EXIT}

ARGS=
while test -n "${X}"; do
  case ${X} in
    [[:space:]]*)
      X=${X# }
    ;;
    -h| -h*)
      printf "help: ${0##*/} ${X}\n"
      ${EXIT}
    ;;
    -f| -f*)
      case " ${ARGS} " in *' -f '*);; *) ARGS="${ARGS:+${ARGS} }-f";; esac
      X=${X# -?}; X=${X#-?}
    ;;
    -b)
      X=${X#-?}
    ;;
    -[A-z][A-z]*)
      printf %s\\n "-[a-Z][a-Z]*"
      X="-${X#-?}"
    ;;
    #-b* | -[^-]*b*)
    #;;
    #--createpkg)
    #  ARGS=${ARGS/$ARG /}
    #;;
    #--overwrite)
    #  declare -i PKG_OVERWRITE=1
    #  ARGS=${ARGS/$ARG /}
    #;;
    --[[:space:]]*)
      X="${X#*-- } "
      break
    ;;
    #-[a-zA-Z1]*)
    #  continue
    #;;
    #*[a-zA-Z0-9/-]*)
    #  continue
    #;;
    -[A-z]*)
      X="-${X#-?}"
    ;;
    -[!-]*)
      X=${X#-?}
      X=${X%-}
    ;;
    #  printf >&2 "$0: invalid option -- \'$ARG\'\n"
    #  printf >&2 "${0##*/} --help\n"
    *)
      ARGS=${ARGS}; printf %s\\n "X='${X}'" "ARGS='${ARGS}'"
      printf %s\\n "${X}... error"; ${EXIT} 1
    ;;
  esac
done
PKGS="${X%${X##*[![:space:]]}}"
printf %s\\n "PKGS='${PKGS}'"

for MOUNTDIR in $(findmountdir "${PORTS_TMPDIR}"); do
  umount "${MOUNTDIR}" && printf %s\\n "umount ${MOUNTDIR}"
done

mkdir -pm 0755 "${PORTS_TMPDIR}/"

cd "${TMPDIR}/"

check_arch

case ${PKGS} in
  '@'*)
    PKG=${PKGS%% *}; PKGS=${PKGS#$PKG}; PKGS="${PKGS#${PKGS%%[![:space:]]*}}"; PKG=${PKG#@}
    for S in "${PORTS_DIR}/sets/"${PKG}*; do
      test -f "${S}" &&
      while IFS= read -r PKG; do
        PKG=${PKG%%#*}
        PKG="${PKG%${PKG##*[![:space:]]}}"
        test -n "${PKG}" || continue
        PKGS="${PKGS:+${PKGS} }${PKG#${PKG%%[![:space:]]*}}"
      done < ${S}
    done
  ;;
esac
printf %s\\n "PKGS='${PKGS}'"

for PKG in ${PKGS}; do
  CATEGORY=${PKG%/*}
  PN=${PKG#$CATEGORY/}
  test -d "${PORTS_TMPDIR:?}" && rm -r -- "${PORTS_TMPDIR}"
  test -d "${PORTS_DIR}/${PKG}" || continue
  if test ! -d "${PORTS_TMPDIR}/${PKG}"; then
    mkdir -pm 0755 "${PORTS_TMPDIR}/${CATEGORY}"
    cp -ur ${PORTS_DIR}/${PKG}/ ${PORTS_TMPDIR}/${PKG}/ &&
    printf %s\\n "cp -ur ${PORTS_DIR}/${PKG}/ ${PORTS_TMPDIR}/${PKG}/"
  fi
  cd "${PORTS_TMPDIR}/${PKG}/" &&
  if test -x 'build-script.sh'; then
    [ -d "./usr" ] || mkdir -v -m 0755 -- "./usr/"
    [ -d "./usr/ports" ] || mkdir -v -m 0755 -- "./usr/ports/"
    printf %s\\n "cp -ur ${PORTS_DIR}/mksrc.sh ${PORTS_DIR}/profiles ${PORTS_DIR}/scripts -t ./usr/ports/"
    cp -ur ${PORTS_DIR}/mksrc.sh ${PORTS_DIR}/profiles ${PORTS_DIR}/scripts -t ./usr/ports/
    printf %s\\n "cp -ulr ./usr/ports/'mksrc.sh' ./usr/ports/scripts ./usr/ports/profiles/* ."
    cp -ulr ./usr/ports/'mksrc.sh' ./usr/ports/scripts ./usr/ports/profiles/* .

    export USER XPN PF PV WORKDIR PKGNAME DPREFIX BUILD_CHROOT LC_ALL BUILD_USER SRC_DIR IUSE SRC_URI PATH
    export XABI SPREFIX EPREFIX DPREFIX PDIR P SN PORTS_DIR DISTDIR DISTSOURCE FILESDIR INSTALL_DIR S SDIR

    PDIR=${PWD}
    PATH="${PATH:+${PATH}:}${PDIR}/misc.d:${PDIR}/etools.d"

    . "${PDIR%/}/etools.d/"build-functions

    printf %s\\n "ABI_BUILD=${ABI} ./build-script.sh ${ARGS} 2>&1"
    if test "X$(arch)" != "X$(check_arch)"; then
      ABI_BUILD=${ABI} setarch linux32 ./build-script.sh ${ARGS} 2>&1
    else
      ABI_BUILD=${ABI} ./build-script.sh ${ARGS} 2>&1
    fi
  else
    cp -ur ${PORTS_DIR}/'mksrc.sh' ${PORTS_DIR}/profiles ${PORTS_TMPDIR}/
    printf %s\\n "NSH=1 RMBUILD=0 ABI_BUILD=${ABI} ${PORTS_TMPDIR}/mksrc.sh ${ARGS} 2>&1" &&
    if test "X$(arch)" != "X$(check_arch)"; then
      NSH='1' RMBUILD='0' ABI_BUILD=${ABI} setarch linux32 ${PORTS_TMPDIR}/mksrc.sh ${ARGS} 2>&1
    else
      NSH='1' RMBUILD='0' ABI_BUILD=${ABI} ${PORTS_TMPDIR}/mksrc.sh ${ARGS} 2>&1
    fi
  fi
  cd "${TMPDIR}/"
done | tee -a ${LOGFILE:?required <LOGFILE>}
