#override NETSURF_USE_DUKTAPE := NO
override NETSURF_STRIP_BINARY := YES

#override NETSURF_FB_FRONTEND := linux
override NETSURF_FB_FRONTEND := sdl
override NETSURF_FB_FONTPATH := /usr/share/fonts/dejavu:/usr/share/fonts/liberation-fonts
