#!/bin/sh
set -e -u -f

BUILD_DIR=${BUILD_DIR:-$WORKDIR}

die() {
  printf %s\\n "${*:-Failed: ${_} build... error}" >&2
  exit 1
}

. runverb \
ninja -j "$(nproc)" -C "${BUILD_DIR:?}/build" || die "Build... Failed"
